### ISSUE TITLE
Fetch Source via URL (Github, Soucify, etc)

### ISSUE THREAD

**Issue by 0xCourtney** [solidstate-network/hardhat-bytecode-exporter#7]
reference: https://github.com/solidstate-network/hardhat-bytecode-exporter/pull/6#issuecomment-1278928220

**Comment by ItsNickBarry** [comment]
If bytecode is published to GitHub or similar, it can be added as an NPM dependency.  Then, is there any reason to re-export it?

**Comment by 0xCourtney** [comment]
> If bytecode is published to GitHub or similar, it can be added as an NPM dependency. Then, is there any reason to re-export it?

I didn't really explain this but I was thinking that the plugin would fetch the source and then export the bytecode. Otherwise, I agree if the bytecode is already available somewhere it doesn't make sense to export it again.

**Comment by ItsNickBarry** [comment]
This should be a feature of [hardhat-dependency-compiler](https://github.com/ItsNickBarry/hardhat-dependency-compiler) instead.  If that plugin could download contract source code from a URL or by address from a blockchain explorer, then the compilation artifacts would be available not only to this plugin but also to [hardhat-abi-exporter](https://github.com/ItsNickBarry/hardhat-abi-exporter) and `hardhat-ethers` (for deployment purposes).

Anyway, in the particular case of bytecode extraction, it's fairly simple to just use the `eth_getCode` RPC method.

Closing this in favor of this: https://github.com/ItsNickBarry/hardhat-dependency-compiler/issues/22
