### ISSUE TITLE
Omit `0x` Flag

### ISSUE THREAD

**Issue by 0xCourtney** [solidstate-network/hardhat-bytecode-exporter#8]
There may be a case where users do not want the `0x` header in their `.bin` file. If this is omitted, the hex validation would also need to take this into account.

https://github.com/ItsNickBarry/hardhat-abi-exporter/issues/44

**Comment by ItsNickBarry** [comment]
I'll remove and publish a new version.  If anyone needs it for some reason, we can add a flag to include it.

**Comment by ItsNickBarry** [comment]
Fixed in `1.1.0`.
